---
- name: Add Host to Temporary Inventory
  host:
    name: "{{ server_hostname }}" # From preceding roles or survey
    description: Temporary inventory host for server build
    inventory: "{{ tower_inventory_name }}" # From role defaults
    state: present
    controller_host: "{{ tower_host_name }}" # From role vars
    validate_certs: "{{ tower_validate_certs }}" # From role defaults
    
    
