---

- name: Set Guest OS IP Address
  gather_facts: no
  hosts: "{{ inventory_host_name }}"
  roles:
    - role: set_ip_address

- name: Set VMware Port Group
  connection: local
  gather_facts: no
  hosts: localhost
  roles:
    - role: set_vm_port_group
      when: vcenter_server != "vcsa7-vcent01.mycompany.net.au" or 
            vcenter_server != "vcsa7-vcent02.mycompany.net.au"
