---
#  Creating a DNS A Record.
- name: Create database server record
  hosts: "{{ server_hostname }}"
  community.windows.win_dns_record:
    computer_name: w2k19-dc01.mycompany.net.au
    name: "{{ server_hostname }}"
    type: "A"
    value: "{{ static_ip }}"
    zone: "{{ win_domain_fqdn }}"

- name: Create matching DNS PTR record
  hosts: "{{ server_hostname }}"
  community.windows.win_dns_record:
    computer_name: w2k19-dc01.mycompany.net.au
    name: "{{ static_ip }}"
    type: "PTR"
    value: "{{ server_hostname }}"
    zone: "1.100.10.in-addr.arpa"
