---
#  Creating a DNS A Record.
- name: Create DNS server record
  community.windows.win_dns_record:
    name: "{{ server_hostname }}"
    type: "A"
    value: "{{ static_ip }}"
    zone: "{{ win_domain_fqdn }}"

- name: Create matching DNS PTR record
  community.windows.win_dns_record:
    name: 10
    type: "PTR"
    value: "{{ server_hostname }}
    zone: "1.100.10.in-addr.arpa"
