---
#  Creating a DNS A Record.
- name: Create DNS server record
  community.windows.win_dns_record:
    name: W2K22-TEST10
    type: "A"
    value: 10.100.1.10
    zone: mycompany.net.au

- name: Create matching DNS PTR record
  community.windows.win_dns_record:
    name: 10.100.1.10
    type: "PTR"
    value: W2K22-TEST10
    zone: "1.100.10.in-addr.arpa"
