---
- name: Set VM IP Address
  vmware_guest:
    hostname: "{{ vcenter_server }}" # From workflow survey
    username: "{{ vcenter_username }}" # From workflow survey
    password: "{{ vcenter_password }}" # From workflow survey
    cluster: "{{ vcenter_cluster }}" # From workflow survey
    datacenter: "{{ vcenter_datacenter }}" # From workflow survey
    datastore: "{{ vm_datastore }}" # From workflow survey
    folder: "/{{ vcenter_datacenter }}/vm" # From workflow survey
    name: "{{ server_hostname | upper }}" # From workflow survey
    networks:
    - name: "{{ vm_static_portgroup }}" # From workflow survey
      device_type: vmxnet3
      type: static
      ip: "{{ static_ip }}" # From workflow survey
      netmask: "{{ subnet_mask }}" # From workflow survey
      gateway: "{{ default_gateway }}" # From workflow survey
    wait_for_ip_address: true
    validate_certs: "{{ vmware_validate_certs }}" # From role defaults
    #delegate_to: localhost
  register: vm_ip_address
- name: Print return information from the previous task
  ansible.builtin.debug:
    msg: vm_ip_address.instance.ipv4.gateway
    #var: vm_ip_address
    #verbosity: 2


