---

- name: Check if CrowdStrike Client Exists
  win_service:
    name: CSFalconService
  register: cs_service

- name: Copy & Install CrowdStrike Client
  block:
    - name: Include Variables for Domain
      include_vars:
        file: "{{ win_domain_fqdn | lower }}.yml"

    - name: Create Temporary Folder
      win_tempfile:
        state: directory
      register: temp_folder_return

    - name: Copy CrowdStrike Client Installation Files
      win_copy:
        remote_src: yes
        src: "{{ win_copy_src }}"
        dest: "{{ temp_folder_return.path }}\\"
      vars:
        ansible_become: yes
        ansible_become_method: runas
        ansible_become_user: "{{ win_domain_admin_user_full }}" # From set_soe_facts role
        ansible_become_pass: "{{ win_domain_admin_password }}"
        ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
    
    - name: Install CrowdStrike Client
      win_command: Deploy-Application.exe -DeployMode Silent -CCID E2E8DA5A76544B55880C173153027511-E1
      args:
        chdir: "{{ temp_folder_return.path }}"
        no_profile: yes
      register: install_return

    - name: Delete Temporary Folder
      win_file:
        path: "{{ temp_folder_return.path }}"
        state: absent