---
- name: Include Variables for Domains
  include_vars:
    file: "{{ win_domain_fqdn | lower }}.yml" # From workflow survey

- hosts: all
  collections:
    - microsoft.ad

- name: join host to AD Domain
  microsoft.ad.membership:
    dns_domain_name: "{{ win_domain_fqdn }}" # From workflow survey
    domain_admin_user: "{{ win_domain_admin_user }}" # From workflow survey
    domain_admin_password: "{{ win_domain_admin_password }}" # From workflow survey
    hostname: "{{ server_hostname }}" # From workflow survey
    domain_ou_path: "{{ domain_ou_dn[server_environment | lower] }}" # From var yaml files
    state: domain
    reboot: true
  register: domain_reg

- name: reboot host after joining workgroup
  ansible.windows.win_reboot:
  when: domain_reg.reboot_required
