---
- name: Join host to the Active Directory Domain
  ansible.windows.win_domain_membership:
    dns_domain_name: "{{ win_domain_fqdn }}"
    hostname: "{{ server_hostname }}"
    domain_admin_user: "{{ win_domain_admin_user }}"
    domain_admin_password: "{{ win_domain_admin_password }}"
    domain_ou_path: "{{ domain_ou_dn[server_environment | lower] }}"
    state: domain
    register: domain_state

- name: Reboot host after domain join
  ansible.windows.win_reboot:
  when: domain_state.reboot_required
