---
- name: Include Variables for Domains
  include_vars:
    file: "{{ win_domain_fqdn | lower }}.yml" # From workflow survey

- name: Add Windows server to Active Directory
  microsoft.ad.membership:
    name: "{{ inventory_hostname }}"
    domain_admin_user: "{{ win_domain_admin_user }}"
    domain_admin_password: "{{ win_domain_admin_password }}"
    domain_name: "{{ win_domain_fqdn }}"
    organizational_unit: "{{ domain_ou_dn[server_environment | lower] }}"
    state: domain
  register: domain_join

- name: Reboot the server to complete domain join
  win_reboot:
    when: domain_join.reboot_required
